version: 2.1
orbs:
  android: circleci/android@2.0

# Workflows orchestrate a set of jobs to be run;
workflows:
  version: 2
  build-test-deploy:
    jobs:
      - build-and-unit-test
      - functional-test
 
jobs:
  build-and-unit-test:
    executor:
        name: android/android-machine
        resource-class: large
        tag: 2022.01.1
    working_directory: ~/code
    steps:
      - checkout
      - run:
          name: Check format
          command: make check-format
      - run:
          name: Check style
          command: make checkstyle
      - run:
          name: Assemble phone release
          command: make assemble-phone-release
      - run:
          name: Javadoc
          command: make javadoc
      - run:
          name: Download Codecov Uploader
          command: |
            curl -s https://codecov.io/bash > codecov;
            VERSION=$(grep 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
            for i in 1 256 512
            do
              shasum -a $i -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM") ||
              shasum -a $i -c <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM" | grep -w "codecov")
            done
      - run:
          name: Run Unit Tests
          command: make unit-test-coverage
      - store_test_results:
          path: code/android-campaignclassic-library/build/test-results/testPhoneDebugUnitTest
      - run:
          name: Upload Core unit test coverage
          command: |
            bash ./codecov -v -X s3 -c -D "./ci/unit-test/build/reports" -F unit-tests

  functional-test:
    executor:
        name: android/android-machine
        resource-class: large
        tag: 2022.01.1
    steps:
      - checkout
      - android/start-emulator-and-run-tests:
          #   It should match the name seen in the "sdkmanager --list" output
          system-image: system-images;android-29;default;x86
          #   The command to be run, while waiting for emulator startup
          post-emulator-launch-assemble-command: make assemble-phone
          #   The test command
          test-command: make functional-test-coverage

      # code coverage
      - run:
          name: Upload Code Coverage Report
          command: |
            curl -s https://codecov.io/bash > codecov;
            VERSION=$(grep 'VERSION=\"[0-9\.]*\"' codecov | cut -d'"' -f2);
            for i in 1 256 512
            do
              shasum -a $i -c --ignore-missing <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM") ||
              shasum -a $i -c <(curl -s "https://raw.githubusercontent.com/codecov/codecov-bash/${VERSION}/SHA${i}SUM" | grep -w "codecov")
            done
            bash ./codecov -v -X s3 -c -D "./code/android-campaignclassic-library/build/reports/coverage/androidTest/phone/debug" -F functional-tests

